INFO  | 04/14/2020 06:00:42 PM | File run_exp.py           | Line 26    | Writing log file to exp/GRAN\GRANMixtureBernoulli_transport_2020-Apr-14-18-00-42_16548\log_exp_16548.txt
INFO  | 04/14/2020 06:00:42 PM | File run_exp.py           | Line 27    | Exp instance id = 16548
INFO  | 04/14/2020 06:00:42 PM | File run_exp.py           | Line 28    | Exp comment = None
INFO  | 04/14/2020 06:00:42 PM | File run_exp.py           | Line 29    | Config =
INFO  | 04/14/2020 06:00:42 PM | File gran_runner.py       | Line 139   | Train/val/test = 8/2/2
INFO  | 04/14/2020 06:00:42 PM | File gran_runner.py       | Line 152   | No Edges vs. Edges in training set = 120.54326923076923
ERROR | 04/14/2020 06:00:47 PM | File run_exp.py           | Line 42    | Traceback (most recent call last):
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\run_exp.py", line 38, in main
    runner.train()
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\runner\gran_runner.py", line 264, in train
    train_loss = model(*batch_fwd).mean()
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\utils\data_parallel.py", line 104, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\model\gran_mixture_bernoulli.py", line 495, in forward
    pos_loss = positional_loss(pos_true, pos_pred, self.pos_loss_func)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\model\gran_mixture_bernoulli.py", line 542, in positional_loss
    pos_loss = torch.sqrt(pos_loss_func(pos_true, pos_pred))
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\loss.py", line 431, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\functional.py", line 2185, in mse_loss
    ret = (input - target) ** 2
RuntimeError: The size of tensor a (159) must match the size of tensor b (50) at non-singleton dimension 0

