INFO  | 03/25/2020 03:54:20 PM | File run_exp.py           | Line 26    | Writing log file to exp/GRAN\GRANMixtureBernoulli_transport_2020-Mar-25-15-54-20_14576\log_exp_14576.txt
INFO  | 03/25/2020 03:54:20 PM | File run_exp.py           | Line 27    | Exp instance id = 14576
INFO  | 03/25/2020 03:54:20 PM | File run_exp.py           | Line 28    | Exp comment = None
INFO  | 03/25/2020 03:54:20 PM | File run_exp.py           | Line 29    | Config =
INFO  | 03/25/2020 03:54:20 PM | File gran_runner.py       | Line 124   | Train/val/test = 8/2/2
INFO  | 03/25/2020 03:54:20 PM | File gran_runner.py       | Line 137   | No Edges vs. Edges in training set = 2.0
ERROR | 03/25/2020 03:54:26 PM | File run_exp.py           | Line 42    | Traceback (most recent call last):
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\run_exp.py", line 38, in main
    runner.train()
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\runner\gran_runner.py", line 249, in train
    train_loss = model(*batch_fwd).mean()
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\utils\data_parallel.py", line 104, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\model\gran_mixture_bernoulli.py", line 463, in forward
    pos_loss = positional_loss(pos_true, pos_pred, pos_loss_function, subgraph_idx)
NameError: name 'pos_loss_function' is not defined

