INFO  | 03/25/2020 12:50:15 PM | File run_exp.py           | Line 26    | Writing log file to exp/GRAN\GRANMixtureBernoulli_grid_2020-Mar-25-12-50-15_26716\log_exp_26716.txt
INFO  | 03/25/2020 12:50:15 PM | File run_exp.py           | Line 27    | Exp instance id = 26716
INFO  | 03/25/2020 12:50:15 PM | File run_exp.py           | Line 28    | Exp comment = None
INFO  | 03/25/2020 12:50:15 PM | File run_exp.py           | Line 29    | Config =
INFO  | 03/25/2020 12:50:16 PM | File gran_runner.py       | Line 124   | Train/val/test = 80/20/20
INFO  | 03/25/2020 12:50:16 PM | File gran_runner.py       | Line 137   | No Edges vs. Edges in training set = 111.70632737276479
ERROR | 03/25/2020 12:50:16 PM | File run_exp.py           | Line 42    | Traceback (most recent call last):
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\run_exp.py", line 38, in main
    runner.train()
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\runner\gran_runner.py", line 161, in train
    train_dataset = eval(self.dataset_conf.loader_name)(self.config, self.graphs_train, tag='train')
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\dataset\gran_data.py", line 50, in __init__
    data = self._get_graph_data(G)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\dataset\gran_data.py", line 105, in _get_graph_data
    node_x_list_bfs.append(G.nodes(data=True)[node_list_bfs[i]]["x"])
KeyError: 'x'

