INFO  | 04/14/2020 05:50:03 PM | File run_exp.py           | Line 26    | Writing log file to exp/GRAN\GRANMixtureBernoulli_transport_2020-Apr-14-17-50-03_15420\log_exp_15420.txt
INFO  | 04/14/2020 05:50:03 PM | File run_exp.py           | Line 27    | Exp instance id = 15420
INFO  | 04/14/2020 05:50:03 PM | File run_exp.py           | Line 28    | Exp comment = None
INFO  | 04/14/2020 05:50:03 PM | File run_exp.py           | Line 29    | Config =
INFO  | 04/14/2020 05:50:03 PM | File gran_runner.py       | Line 139   | Train/val/test = 8/2/2
INFO  | 04/14/2020 05:50:03 PM | File gran_runner.py       | Line 152   | No Edges vs. Edges in training set = 459.792093704246
ERROR | 04/14/2020 05:50:11 PM | File run_exp.py           | Line 42    | Traceback (most recent call last):
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\run_exp.py", line 38, in main
    runner.train()
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\runner\gran_runner.py", line 264, in train
    train_loss = model(*batch_fwd).mean()
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\utils\data_parallel.py", line 104, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\model\gran_mixture_bernoulli.py", line 487, in forward
    node_pos=node_pos)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\model\gran_mixture_bernoulli.py", line 276, in _inference
    node_feat[node_idx_feat], edges, edge_feat=att_edge_feat, node_pos=node_pos[:,node_idx_feat])
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\model\gran_mixture_bernoulli.py", line 122, in forward
    state = self._prop(state, edge, edge_feat=edge_feat, node_pos=node_pos, layer_idx=ii)
  File "c:\Users\olive\OneDrive\Dokumenter\GitHub\GRAN\model\gran_mixture_bernoulli.py", line 102, in _prop
    state = self.update_func[layer_idx](state_msg, state)
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\olive\Anaconda3\envs\Bachelor\lib\site-packages\torch\nn\modules\rnn.py", line 1022, in forward
    self.bias_ih, self.bias_hh,
RuntimeError: CUDA out of memory. Tried to allocate 386.00 MiB (GPU 0; 6.00 GiB total capacity; 4.30 GiB already allocated; 194.52 MiB free; 213.26 MiB cached)

